# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: commandvel.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'commandvel.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63ommandvel.proto\x12\x10\x43ommandVelBridge\"\"\n\x0e\x43ommandRequest\x12\x10\n\x08\x64rone_id\x18\x01 \x01(\r\"E\n\nCommandVel\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0b\n\x03vel\x18\x02 \x01(\x02\x12\x0b\n\x03rot\x18\x03 \x01(\x02\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x32m\n\x17\x43ommandVelBridgeService\x12R\n\x0ePullCommandVel\x12 .CommandVelBridge.CommandRequest\x1a\x1c.CommandVelBridge.CommandVel0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'commandvel_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMANDREQUEST']._serialized_start=38
  _globals['_COMMANDREQUEST']._serialized_end=72
  _globals['_COMMANDVEL']._serialized_start=74
  _globals['_COMMANDVEL']._serialized_end=143
  _globals['_COMMANDVELBRIDGESERVICE']._serialized_start=145
  _globals['_COMMANDVELBRIDGESERVICE']._serialized_end=254
# @@protoc_insertion_point(module_scope)
