# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: getcontrol_bridge.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'getcontrol_bridge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17getcontrol_bridge.proto\x12\x10GetControlBridge\"\x07\n\x05\x45mpty\"D\n\x0c\x43ontrolState\x12\n\n\x02id\x18\x01 \x01(\r\x12\x15\n\rcontrol_value\x18\x02 \x01(\x08\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x32\x64\n\x17GetControlBridgeService\x12I\n\x0cPullControls\x12\x17.GetControlBridge.Empty\x1a\x1e.GetControlBridge.ControlState0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'getcontrol_bridge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=45
  _globals['_EMPTY']._serialized_end=52
  _globals['_CONTROLSTATE']._serialized_start=54
  _globals['_CONTROLSTATE']._serialized_end=122
  _globals['_GETCONTROLBRIDGESERVICE']._serialized_start=124
  _globals['_GETCONTROLBRIDGESERVICE']._serialized_end=224
# @@protoc_insertion_point(module_scope)
