# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import navdata_push_pb2 as navdata__push__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in navdata_push_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NavdataPushServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PushNavdataStream = channel.stream_unary(
                '/NavdataPush.NavdataPushService/PushNavdataStream',
                request_serializer=navdata__push__pb2.NavdataMsg.SerializeToString,
                response_deserializer=navdata__push__pb2.Ack.FromString,
                _registered_method=True)


class NavdataPushServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PushNavdataStream(self, request_iterator, context):
        """Bridge sends continuous telemetry stream
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NavdataPushServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PushNavdataStream': grpc.stream_unary_rpc_method_handler(
                    servicer.PushNavdataStream,
                    request_deserializer=navdata__push__pb2.NavdataMsg.FromString,
                    response_serializer=navdata__push__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'NavdataPush.NavdataPushService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('NavdataPush.NavdataPushService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NavdataPushService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PushNavdataStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/NavdataPush.NavdataPushService/PushNavdataStream',
            navdata__push__pb2.NavdataMsg.SerializeToString,
            navdata__push__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
