# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sendmission_bridge.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'sendmission_bridge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18sendmission_bridge.proto\x12\x11SendMissionBridge\"\x07\n\x05\x45mpty\"C\n\x0cMissionState\x12\n\n\x02id\x18\x01 \x01(\r\x12\x14\n\x0cmission_json\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x32g\n\x18SendMissionBridgeService\x12K\n\x0cPullMissions\x12\x18.SendMissionBridge.Empty\x1a\x1f.SendMissionBridge.MissionState0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sendmission_bridge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=47
  _globals['_EMPTY']._serialized_end=54
  _globals['_MISSIONSTATE']._serialized_start=56
  _globals['_MISSIONSTATE']._serialized_end=123
  _globals['_SENDMISSIONBRIDGESERVICE']._serialized_start=125
  _globals['_SENDMISSIONBRIDGESERVICE']._serialized_end=228
# @@protoc_insertion_point(module_scope)
